item1:
  headline: "Paris Themed Watercolor Style Backpack"
  link: "https://shop.scienceofgifts.com/products/paris-watercolor-art-backpack"
  source: "scienceofgifts"
  buy-text: "shop | $44"
  img: "paris-themed-watercolor-backpack"
  img-alt: "Paris Backpack"
  description: "Paris Themed Watercolor Style Backpack"
  gg: "Paris Themed Watercolor Style Backpack"
  ideal-for: "test"

item2:
  headline: "Paris Themed Tumbler"
  link: "https://shop.scienceofgifts.com/products/creative-paris-themed-tumbler"
  source: "scienceofgifts"
  buy-text: "shop | $29"
  img: "paris-themed-tumbler"
  img-alt: "Paris Tumbler"
  description: "Paris Themed Tumbler - Eiffel Tower Tumbler for Paris Lovers"
